### ISSUE TITLE
Compile optimization on FMU and Node

### ISSUE THREAD

**Issue by rega0051** [bolderflight/RAPTRS#21]
FMU and Node compilation optimization is currently set to -O. Previously, using the Arduino IDE the default was -O3.

**Comment by flybrianfly** [comment]
Jotting down some notes...

Current teensy Makefile (https://github.com/PaulStoffregen/cores/blob/master/teensy3/Makefile) uses Os (size optimization). Arduino optimization depends on release version and optimization settings. O3 or O2 would likely be preferable. Need to test compile to ensure that it works.
